version: '3'

services:
  api:
    image: openjdk:8-jre-alpine
    ports:
      - 8080:8080
    volumes:
       - .:/home
    tty: true
    entrypoint:
        - java
        - -jar
        - /home/target/truelogic-1.0-SNAPSHOT.jar
        - server
        - /home/config.yml
    depends_on:
      - db
    networks:
      - app-tier
  db:
     image: mysql:5.7.20
     environment:
         - MYSQL_USER=root
         - MYSQL_ALLOW_EMPTY_PASSWORD=yes
         - MYSQL_DATABASE=blog
     ports:
       - 3306:3306
     command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
     networks:
           app-tier:
             aliases:
              - db
networks:
  app-tier:
    driver: bridge